debug: false

node:
  uuid: "19790de5-6d07-40e2-a4d9-a22d3e625ba0"
  key: "2fb0bbc4f8b867e674e198d44a035d883536f6472c5997cc5b2146fb5bebfd71"

docker:
  base_port: 8089
  max_port: 8124

api:
  host: 0.0.0.0
  port: 8089
  ssl:
    enabled: false

default: 25570

remote: "http://localhost:8000"
